---
- hosts: centoslinux

  remote_user: root
  become: true
  tasks: 
   - name: apache server listen on port 4545
     lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 4545" state=present
     notify: 
      - restart httpd
  handlers: 
   - name: restart httpd
     service: name=httpd state=restarted
