---
- hosts: server1
  remote_user: root
  become: true
  tasks:
    - name: converting file to zip file
      archive: 
        path: /home/jeet/fileone
        dest: /home/jeet/fileone.zip
        format: zip
